version: 2
jobs:
  build:
    docker:
      - image: quay.io/3scale/s2i-openresty-centos7:1.11.2.3-5
        environment:
          TEST_NGINX_BINARY: openresty
          TEST_NGINX_ERROR_LOG: tmp/logs/prove.log
    working_directory: /opt/app-root/wildcard_service
    steps:
      - checkout
      - run: luarocks make *.rockspec
      - run: /usr/local/openresty/luajit/bin/apicast-cli busted
      - run: mkdir -p tmp/logs
      - run: prove
      - store_artifacts:
          path: t/servroot
          destination: prove
      - store_artifacts:
          path: tmp/logs
          destination: logs
